site_name: OpenMod Documentation

theme:
  name: material
  favicon: logo.svg
  logo: logo.svg
  palette:
    scheme: slate
    primary: blue grey
    accent: cyan
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    
markdown_extensions:
  - toc:
      permalink: true